### ISSUE TITLE
add back-end repo on github?

### ISSUE THREAD

**Issue by bcolloran** [PENGUINLIONG/rtaichi#2]
hi @PENGUINLIONG , thank you for making this code available. Would it be possible to also put the backend crate `taichi-runtime` on Github? I'm very interested in trying to use Taichi with Rust, and I'd like to see how the whole stack was built, but I only see a Github repo for the `rtaichi` frontend. 

Thanks!

**Comment by bcolloran** [comment]
oh i see that perhaps `taichi-sys` would be useful as well. Thanks @PENGUINLIONG !!

**Comment by PENGUINLIONG** [comment]
They are available [here](https://github.com/PENGUINLIONG/taichi-rs). The thing was published in an entire rush for the hackathon so things are a bit poorly organized.

**Comment by bcolloran** [comment]
Thanks for getting back to me @PENGUINLIONG! 

That link (https://github.com/PENGUINLIONG/taichi-rs) gives me a 404 -- is it maybe a private repo currently?

No problem how it's organized, I know it was for a hackathon. It will be a big help just to be able to look :-)

**Comment by PENGUINLIONG** [comment]
i just realized that. it's public now. 😂
